<?php
define("DB_HOST", $_ENV['DB_HOST']);
define("DB_USERNAME", $_ENV['DB_USERNAME']);
define("DB_PASSWORD", $_ENV['DB_PASSWORD']);
define("DB_DATABASE_NAME", $_ENV['DB_DATABASE']);
define("JWT_SECRET_KEY", $_ENV['JWT_SECRET_KEY']);
define("JWT_ALGORITHM", $_ENV['JWT_ALGORITHM']);
define("JWT_EXPIRATION_TIME", $_ENV['JWT_EXPIRATION_TIME']);
define("JWT_ISSUER", $_ENV['JWT_ISSUER']);
define("JWT_AUDIENCE", $_ENV['JWT_AUDIENCE']);